/* eslint-disable @typescript-eslint/no-unused-vars */
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowLeft, BrainCircuit, Send } from "lucide-react";
import { auth } from "../firebaseClient";
import { getProject, renameFluidProgramsProject, sendFluidProgramsMessage, type FluidProgramsData } from "../fluidlab/projects";
import "./fluid-programs.css";

export default function FluidPrograms({ projectId, navigate, onDirtyChange }: { projectId: string; navigate: (path: string) => void; onDirtyChange: (dirty: boolean) => void }) {
  const [name, setName] = useState(""), [data, setData] = useState<FluidProgramsData>({ version: 1, messages: [] }), [revision, setRevision] = useState(0), [message, setMessage] = useState(""), [remaining, setRemaining] = useState(50), [state, setState] = useState<"loading" | "saved" | "editing" | "saving" | "sending" | "failed" | "conflict">("loading"), [error, setError] = useState("");
  const bottom = useRef<HTMLDivElement>(null), loaded = useRef(false), revisionRef = useRef(0), dataRef = useRef(data), nameRef = useRef(name);
  useEffect(() => { dataRef.current = data; nameRef.current = name; }, [data, name]);
  useEffect(() => { if (!auth.currentUser) { navigate(`/signin?returnTo=${encodeURIComponent(location.pathname)}`); return; } let active = true; void getProject(projectId).then(({ project, remaining: allowance }) => { if (!active) return; if (project.type !== "fluid-programs" || !project.data || !("messages" in project.data)) throw new Error(); setName(project.name); setData(project.data); dataRef.current = project.data; setRevision(project.revision); revisionRef.current = project.revision; setRemaining(allowance ?? 50); loaded.current = true; setState("saved"); }).catch(() => { if (active) { setError("This Fluid Programs project could not be opened."); setState("failed"); } }); return () => { active = false; }; }, [navigate, projectId]);
  useEffect(() => {
    bottom.current?.scrollIntoView({ behavior: "smooth" });
  }, [data.messages.length, state]);
  useEffect(() => { const dirty = state === "editing" || state === "saving" || state === "sending" || state === "failed" || state === "conflict" || Boolean(message.trim()); onDirtyChange(dirty); const leave = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; addEventListener("beforeunload", leave); return () => removeEventListener("beforeunload", leave); }, [message, onDirtyChange, state]);
  const saveName = useCallback(async () => { if (!nameRef.current.trim() || state === "sending") return; setState("saving"); try { const saved = await renameFluidProgramsProject(projectId, nameRef.current.trim(), dataRef.current, revisionRef.current, crypto.randomUUID()); revisionRef.current = saved.revision; setRevision(saved.revision); setState("saved"); } catch (requestError) { const code = String((requestError as { code?: string }).code || ""); setState(code.includes("aborted") ? "conflict" : "failed"); setError(code.includes("aborted") ? "This conversation changed elsewhere. Reload before continuing." : "The project name could not be saved."); } }, [projectId, state]);
  useEffect(() => { if (!loaded.current || state !== "editing") return; const timer = window.setTimeout(() => void saveName(), 900); return () => clearTimeout(timer); }, [name, saveName, state]);
  const submit = async (event: FormEvent) => { event.preventDefault(); const text = message.trim(); if (!text || state === "sending" || remaining <= 0) return; setMessage(""); setError(""); setState("sending"); try { const result = await sendFluidProgramsMessage(projectId, text, revisionRef.current, crypto.randomUUID()); if (!result.project.data || !("messages" in result.project.data)) throw new Error(); setData(result.project.data); dataRef.current = result.project.data; revisionRef.current = result.project.revision; setRevision(result.project.revision); setRemaining(result.remaining); setState("saved"); } catch (requestError) { const code = String((requestError as { code?: string }).code || ""); setMessage(text); if (code.includes("aborted")) setState("conflict"); else setState("failed"); setError(code.includes("resource-exhausted") ? "The conversation or daily allowance is full. Start a new conversation or try again tomorrow." : code.includes("aborted") ? "This conversation changed elsewhere. Reload before continuing." : "The assistant could not answer. Your message was not saved; try again."); } };
  return <main className="programs-shell"><header><button onClick={() => navigate("/account")}><ArrowLeft/><span>Back to Projects</span></button><div><BrainCircuit/>Uniq<strong>Energy</strong><span>/ Fluid Programs</span></div><small>{state === "sending" ? "Thinking…" : state === "saving" ? "Saving…" : state === "saved" ? "Saved" : state === "conflict" ? "Reload required" : state === "failed" ? "Needs attention" : "Loading…"}</small></header><section className="programs-workspace"><aside><span>Conversation project</span><input aria-label="Project name" maxLength={100} value={name} onChange={(event) => { setName(event.target.value); setState("editing"); }}/><p><b>{remaining}</b> of 50 AI messages remaining today</p><div className="programs-notice"><strong>Educational assistant</strong><span>Field decisions and treatment programs require review by a qualified drilling-fluids engineer using current well data.</span></div></aside><section className="chat-panel"><div className="chat-heading"><BrainCircuit/><div><h1>Fluid Programs</h1><p>Ask about drilling-fluid systems, properties, testing, and troubleshooting.</p></div></div><div className="chat-messages" aria-live="polite">{data.messages.length === 0 && <div className="chat-empty"><BrainCircuit/><h2>Start a drilling-fluid conversation</h2><p>Try asking about rheology, fluid loss, contamination, system selection, or field testing.</p></div>}{data.messages.map((item) => <article key={item.id} className={item.role}><span>{item.role === "user" ? "You" : "Fluid Programs"}</span><p>{item.text}</p><time>{new Date(item.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</time></article>)}{state === "sending" && <article className="assistant typing"><span>Fluid Programs</span><p><i/><i/><i/></p></article>}<div ref={bottom}/></div>{error && <div className="chat-error" role="alert">{error}{state === "conflict" && <button onClick={() => location.reload()}>Reload</button>}</div>}<form className="chat-composer" onSubmit={submit}><textarea value={message} maxLength={4000} rows={2} placeholder="Ask about drilling fluids…" onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }}/><button aria-label="Send message" disabled={!message.trim() || state === "sending" || remaining <= 0}><Send/></button></form></section></section></main>;
}
