import assert from "node:assert/strict";
import test from "node:test";
import { randomBytes } from "node:crypto";
import { getApp } from "firebase-admin/app";
import { db, storage } from "../core/firebase.js";
import { hash } from "../apps/invoice-qb/model.js";
import * as service from "../apps/invoice-qb/service.js";

test("emulator: OAuth, shared permissions, atomic candidates, retained documents and deletion", { skip: !process.env.FIRESTORE_EMULATOR_HOST || !process.env.STORAGE_EMULATOR_HOST }, async (t) => {
  const config = { clientId: "client", clientSecret: "private-secret", redirectUri: "https://example.com/callback", encryptionKey: randomBytes(32).toString("base64") };
  let mailbox = "invoices@example.com", failAttachment = false;
  const headers = [{ name: "Subject", value: "Invoice one" }, { name: "From", value: "supplier@example.com" }];
  const sample = { id: "mail1", internalDate: "1700000000000", payload: { headers, parts: [{ mimeType: "text/plain", body: { data: Buffer.from("Invoice body").toString("base64url"), size: 12 } }, { filename: "invoice.pdf", mimeType: "application/pdf", body: { attachmentId: "att1", size: 3 } }] } };
  const originalFetch = globalThis.fetch;
  t.mock.method(getApp().options.credential, "getAccessToken", async () => ({ access_token: "adc", expires_in: 3600 }));
  t.mock.method(globalThis, "fetch", async (url, options) => {
    const target = String(url);
    if (target.includes("secretmanager.googleapis.com")) return Response.json({ payload: { data: Buffer.from(JSON.stringify(config)).toString("base64") } });
    if (target === "https://oauth2.googleapis.com/token") return Response.json({ access_token: "private-access", refresh_token: "private-refresh", scope: "https://www.googleapis.com/auth/gmail.readonly" });
    if (target === "https://oauth2.googleapis.com/revoke") return new Response("");
    if (target.endsWith("/profile")) return Response.json({ emailAddress: mailbox });
    if (target.includes("/attachments/")) return failAttachment ? new Response("", { status: 404 }) : Response.json({ data: Buffer.from("pdf").toString("base64url") });
    if (target.includes("/messages/mail1?")) return Response.json(sample);
    if (target.includes("/messages?")) return Response.json({ messages: [{ id: "mail1" }], nextPageToken: "next" });
    if (target.endsWith("/labels")) return Response.json({ labels: [{ id: "INBOX", name: "Inbox" }] });
    return originalFetch(url, options);
  });
  const request = (uid, data = {}) => ({ auth: { uid, token: { email_verified: true, auth_time: Math.floor(Date.now()/1000), email: `${uid}@example.com` } }, data });
  const admin = request("invoice-admin"), member = request("invoice-member"), outsider = request("invoice-outsider");
  const callback = async (state) => { let location; await service.invoiceQbOauthCallback({ query: { state, code: "code" } }, { set() {}, redirect(value) { location = value; } }); return location; };
  try {
    for (const [uid, role, enabledMiniApps] of [["invoice-admin", "admin", []], ["invoice-member", "employee", ["invoice-qb"]], ["invoice-outsider", "member", []]]) await db.doc(`users/${uid}`).set({ schemaVersion: 2, email: `${uid}@example.com`, status: "active", role, enabledMiniApps });
    await assert.rejects(service.invoiceQbQueue.run({ data: {} }), (e) => e.code === "unauthenticated");
    await assert.rejects(service.invoiceQbQueue.run(outsider), (e) => e.code === "permission-denied");
    await assert.rejects(service.invoiceQbConnect.run(member), (e) => e.code === "permission-denied");
    const start = await service.invoiceQbConnect.run(admin), state = new URL(start.url).searchParams.get("state");
    assert.match(await callback(state), /success$/);
    assert.match(await callback(state), /failed$/);
    const saved = (await db.doc("invoiceQbPrivate/connection").get()).data();
    assert.notEqual(saved.refreshToken, "private-refresh");
    assert.equal((await service.invoiceQbConnection.run(member)).email, mailbox);
    assert.equal(JSON.stringify(await service.invoiceQbConnection.run(member)).includes("private-refresh"), false);
    const expired = new URL((await service.invoiceQbConnect.run(admin)).url).searchParams.get("state");
    await db.doc(`invoiceQbOauth/${hash(expired)}`).update({ expires: 0 });
    assert.match(await callback(expired), /failed$/);
    const revokedAdmin = new URL((await service.invoiceQbConnect.run(admin)).url).searchParams.get("state");
    await db.doc("users/invoice-admin").update({ status: "disabled" });
    assert.match(await callback(revokedAdmin), /failed$/);
    await db.doc("users/invoice-admin").update({ status: "active" });
    const listed = await service.invoiceQbMessages.run(request("invoice-member", { label: "INBOX" }));
    assert.equal(listed.cursor, "next"); assert.equal(listed.messages[0].queued, false);
    failAttachment = true;
    await assert.rejects(service.invoiceQbAdd.run(request("invoice-member", { messageId: "mail1", parts: ["body", "0_1"] })), (e) => e.code === "not-found");
    assert.equal((await service.invoiceQbQueue.run(member)).entries.length, 0);
    failAttachment = false;
    const results = await Promise.allSettled([1, 2].map(() => service.invoiceQbAdd.run(request("invoice-member", { messageId: "mail1", parts: ["body", "0_1"] }))));
    assert.equal(results.filter((r) => r.status === "fulfilled").length, 1);
    assert.equal(results.find((r) => r.status === "rejected").reason.code, "already-exists");
    const queued = (await service.invoiceQbQueue.run(member)).entries[0];
    assert.equal(queued.documents.length, 2);
    assert.equal(queued.documents[0].path, undefined);
    assert.equal(queued.sourcePath, undefined);
    assert.equal((await service.invoiceQbMessages.run(request("invoice-member", {}))).messages[0].queued, true);
    await service.invoiceQbUpdate.run(request("invoice-member", { id: queued.id, status: "ignored", notes: "Duplicate in QB", revision: 1 }));
    await assert.rejects(service.invoiceQbUpdate.run(request("invoice-member", { id: queued.id, status: "queued", notes: "", revision: 1 })), (e) => e.code === "aborted");
    await service.invoiceQbUpdate.run(request("invoice-member", { id: queued.id, status: "queued", notes: "Reopened", revision: 2 }));
    await service.invoiceQbDisconnect.run(admin);
    assert.equal((await service.invoiceQbConnection.run(member)).connected, false);
    assert.equal((await service.invoiceQbQueueBody.run(request("invoice-member", { id: queued.id }))).body, "Invoice body");
    mailbox = "new-invoices@example.com";
    assert.match(await callback(new URL((await service.invoiceQbConnect.run(admin)).url).searchParams.get("state")), /success$/);
    assert.equal((await service.invoiceQbQueue.run(member)).entries.length, 1);
    const separate = await service.invoiceQbAdd.run(request("invoice-member", { messageId: "mail1", parts: ["body", "0_1"], separate: true }));
    assert.equal(separate.ids.length, 2);
    const privateEntry = (await db.doc(`invoiceQbQueue/${queued.id}`).get()).data();
    await service.invoiceQbRemove.run(request("invoice-member", { id: queued.id }));
    assert.equal((await storage.bucket().file(privateEntry.documents[0].path).exists())[0], false);
    assert.equal((await db.doc(`invoiceQbClaims/${privateEntry.documents[0].claim}`).get()).exists, false);
    await db.doc("users/invoice-member").update({ status: "disabled" });
    await assert.rejects(service.invoiceQbQueue.run(member), (e) => e.code === "permission-denied");
  } finally {
    for (const name of ["invoiceQbPrivate", "invoiceQbQueue", "invoiceQbClaims", "invoiceQbOauth"]) await db.recursiveDelete(db.collection(name));
    for (const uid of ["invoice-admin", "invoice-member", "invoice-outsider"]) await db.doc(`users/${uid}`).delete();
    await storage.bucket().deleteFiles({ prefix: "invoice-qb/" });
  }
});
