// @vitest-environment jsdom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { beforeEach, afterEach, it, expect, vi } from "vitest";
const session = vi.hoisted(() => ({ user: { role: "admin" } }));
vi.mock("../../portal/AuthContext", () => ({ usePortalAuth: () => session }));
vi.mock("./api", () => ({ connection: vi.fn(), labels: vi.fn(), messages: vi.fn(), message: vi.fn(), add: vi.fn(), queue: vi.fn(), queueBody: vi.fn(), extract: vi.fn(), saveDraft: vi.fn(), update: vi.fn(), remove: vi.fn(), connect: vi.fn(), disconnect: vi.fn(), documentBlob: vi.fn() }));
vi.mock("pdfjs-dist", () => ({ GlobalWorkerOptions: {}, getDocument: vi.fn() }));
import * as api from "./api";
import InvoiceQb, { previewable } from "./InvoiceQb";
let root: Root, host: HTMLDivElement;
const summary = { id: "mail1", subject: "Supplier invoice", sender: "supplier@example.com", date: "2026-09-01T12:00:00Z", attachmentCount: 1, queued: false };
beforeEach(() => {
  vi.resetAllMocks(); session.user = { role: "admin" };
  Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });
  host = document.createElement("div"); document.body.append(host); root = createRoot(host);
  vi.mocked(api.connection).mockResolvedValue({ configured: true, connected: true, email: "invoices@example.com" });
  vi.mocked(api.labels).mockResolvedValue({ labels: [{ id: "INBOX", name: "Inbox" }] });
  vi.mocked(api.messages).mockResolvedValue({ messages: [summary], cursor: null });
  vi.mocked(api.message).mockResolvedValue({ ...summary, body: "Invoice text", html: '<script>alert(1)</script><table><tr><td>Invoice text</td></tr></table><img src="https://tracker.test">', attachments: [{ id: "0_1", name: "invoice.pdf", mime: "application/pdf", size: 3 }] });
  vi.mocked(api.queue).mockResolvedValue({ entries: [], cursor: null });
  vi.mocked(api.add).mockResolvedValue({ ids: ["candidate"] });
  vi.mocked(api.extract).mockResolvedValue({ revision: 2, draft: { documentId: "0_1", transactionType: "vendor_bill", partyName: "Acme Supply", invoiceNumber: "A-104", invoiceDate: "2026-09-01", dueDate: "2026-09-30", currency: "CAD", subtotal: "100.00", tax: "5.00", total: "105.00", lineItems: [{ description: "Parts", quantity: "2", rate: "50.00", amount: "100.00" }], uncertainFields: ["dueDate"], reviewState: "needs_review" } });
  vi.mocked(api.saveDraft).mockImplementation(async (entry, draft) => ({ revision: entry.revision + 1, draft }));
});
afterEach(async () => { await act(async () => root.unmount()); host.remove(); });
const render = async () => { await act(async () => root.render(<InvoiceQb/>)); };
const click = async (text: string) => { const button = [...host.querySelectorAll("button")].find((b) => b.textContent?.includes(text)); expect(button).toBeTruthy(); await act(async () => button!.click()); };
it("browses all mail, safely previews HTML, and queues only selected documents", async () => {
  await render();
  expect(api.messages).toHaveBeenCalledWith({ query: "", from: "", to: "", label: "" }, null);
  await click("Supplier invoice");
  expect(host.querySelector("iframe[sandbox]")).toBeTruthy();
  expect(host.querySelector("iframe")?.getAttribute("srcdoc")).not.toContain("<script");
  expect(host.textContent).toContain("Plain-text email fallback");
  const boxes = host.querySelectorAll<HTMLInputElement>('input[type="checkbox"]');
  await act(async () => boxes[1].click());
  await click("Add to bill queue");
  expect(api.add).toHaveBeenCalledWith("mail1", ["0_1"], false);
  expect(host.textContent).toContain("1 candidate added");
  expect(host.textContent).toContain("Documents in bill queue");
});
it("supports separate candidates and preserves selection when saving fails", async () => {
  await render(); await click("Supplier invoice");
  const boxes = host.querySelectorAll<HTMLInputElement>('input[type="checkbox"]');
  await act(async () => { boxes[0].click(); boxes[1].click(); boxes[2].click(); });
  vi.mocked(api.add).mockRejectedValue(new Error("Attachment unavailable"));
  await click("Add to bill queue");
  expect(api.add).toHaveBeenCalledWith("mail1", ["body", "0_1"], true);
  expect(host.textContent).toContain("Attachment unavailable");
  expect(boxes[0].checked).toBe(true);
});
it("uses pagination and hides admin connection controls from team members", async () => {
  session.user = { role: "employee" };
  vi.mocked(api.messages).mockResolvedValueOnce({ messages: [summary], cursor: "page2" });
  await render();
  expect([...host.querySelectorAll("button")].some((b) => b.textContent === "Connection")).toBe(false);
  await click("Load more");
  expect(api.messages).toHaveBeenLastCalledWith(expect.anything(), "page2");
});
it("shows a useful disconnected setup state and keeps the queue available", async () => {
  vi.mocked(api.connection).mockResolvedValue({ configured: false, connected: false, email: null });
  await render(); await click("Open Connection");
  expect(host.textContent).toContain("Google setup is required");
  await click("Bill Queue");
  expect(host.textContent).toContain("Your bill queue is empty");
  expect(api.messages).not.toHaveBeenCalled();
});
it("previews only passive supported file formats", () => {
  expect(previewable("application/pdf")).toBe(true);
  expect(previewable("image/png")).toBe(true);
  expect(previewable("image/svg+xml")).toBe(false);
  expect(previewable("text/html")).toBe(false);
});
it("extracts a selected queued PDF only after explicit action and allows draft review", async () => {
  const candidate: api.Candidate = { id: "candidate", mailbox: "ap@example.com", messageId: "mail1", subject: "Acme invoice", sender: "Acme", date: "2026-09-01T12:00:00Z", documents: [{ id: "0_1", name: "invoice.pdf", mime: "application/pdf", size: 500 }], createdAt: "2026-09-01T12:00:00Z", addedByName: "Rambod", notes: "", status: "queued", revision: 1 };
  vi.mocked(api.queue).mockResolvedValue({ entries: [candidate], cursor: null });
  vi.mocked(api.queueBody).mockResolvedValue({ body: "Original email source text" });
  await render();
  expect(api.extract).not.toHaveBeenCalled();
  await click("Bill Queue"); await click("Acme invoice");
  expect(host.textContent).toContain("No QuickBooks transaction has been created");
  await click("Extract with AI");
  expect(api.extract).toHaveBeenCalledWith("candidate", "0_1");
  expect(host.textContent).toContain("AI-extracted accounting details");
  expect(host.textContent).toContain("Needs confirmation: dueDate");
  const type = host.querySelector<HTMLSelectElement>(".iq-accounting-draft select");
  expect(type?.value).toBe("vendor_bill");
  await click("Mark ready");
  expect(api.saveDraft).not.toHaveBeenCalled();
  await act(async () => host.querySelector<HTMLInputElement>(".iq-confirm-review input")!.click());
  await click("Mark ready");
  expect(api.saveDraft).toHaveBeenCalledWith(expect.objectContaining({ id: "candidate", revision: 2 }), expect.objectContaining({ reviewState: "ready", reviewConfirmed: true }));
});
