import{describe,expect,it}from"vitest";
import{createProject,emptySection,generateProject,parseProjectJson,validateProject}from"./engineering";
describe("sequential open-hole model",()=>{
 it("builds vertical then inherited straight sections",()=>{const p=createProject(),first=p.openHoleSections[0];first.lengthM=100;const next=emptySection(1,first);next.lengthM=200;p.openHoleSections.push(next);const g=generateProject(p);expect(g.errors).toEqual([]);expect(g.sections[0].end.tvd).toBeCloseTo(100);expect(g.sections[1].start).toEqual(g.sections[0].end);expect(g.sections[1].end.md).toBeCloseTo(300);});
 it("builds, drops, turns and compounds with inherited endpoints",()=>{const p=createProject();p.openHoleSections=[{...emptySection(),lengthM:100},{...emptySection(1),path:"curve",lengthM:300,endInclination:90,endAzimuth:90},{...emptySection(2),path:"curve",lengthM:150,endInclination:60,endAzimuth:90},{...emptySection(3),path:"curve",lengthM:150,endInclination:60,endAzimuth:180},{...emptySection(4),path:"curve",lengthM:150,endInclination:80,endAzimuth:220}];const g=generateProject(p);expect(g.errors).toEqual([]);for(let i=1;i<g.sections.length;i++)expect(g.sections[i].start).toEqual(g.sections[i-1].end);expect(g.sections[1].buildRate).toBeCloseTo(9);expect(g.sections[3].turnRate).toBeCloseTo(18);});
 it("recalculates downstream positions after an earlier edit",()=>{const p=createProject(),second={...emptySection(1),path:"curve"as const,endInclination:90,endAzimuth:90};p.openHoleSections.push(second,{...emptySection(2,second),lengthM:200});const before=generateProject(p).sections.at(-1)!.end;p.openHoleSections[1].endAzimuth=180;const after=generateProject(p).sections.at(-1)!.end;expect(after.easting).not.toBeCloseTo(before.easting);expect(after.md).toBeCloseTo(before.md);});
 it("warns when calculated rates exceed advanced limits",()=>{const p=createProject();p.openHoleSections=[{...emptySection(),path:"curve",lengthM:30,endInclination:30,endAzimuth:20,maxBuildRate:20,maxTurnRate:10}];expect(generateProject(p).warnings).toHaveLength(2);});
 it("calculates cylindrical open-hole capacity",()=>{const p=createProject();p.openHoleSections=[{...emptySection(),lengthM:100,diameterMm:200}];expect(generateProject(p).totalCapacityM3).toBeCloseTo(Math.PI*.2**2/4*100);});
 it("validates inputs and rejects the former construction schema",()=>{const p=createProject();p.openHoleSections[0].lengthM=0;expect(validateProject(p).join()).toMatch(/positive drilled length/);expect(parseProjectJson(JSON.stringify({version:1,name:"old",unitSystem:"metric",wellbores:[]}))).toBeNull();});
});
