export type UnitSystem="metric"|"imperial";
export type PathType="vertical"|"straight"|"curve";
export interface OpenHoleSection{id:string;name:string;diameterMm:number;lengthM:number;path:PathType;endInclination:number|null;endAzimuth:number|null;maxBuildRate:number|null;maxTurnRate:number|null;color:string;confirmed:boolean}
export interface DisplaySettings{selectedSectionId:string|null;labels:boolean;cameraDrift:boolean}
export interface WellProject{version:1;name:string;classification:string;unitSystem:UnitSystem;openHoleSections:OpenHoleSection[];display:DisplaySettings}
export interface Station{md:number;tvd:number;northing:number;easting:number;inclination:number;azimuth:number;sectionId?:string}
export interface DerivedSection{sectionId:string;start:Station;end:Station;dogleg:number;buildRate:number;turnRate:number;capacityM3:number;stations:Station[];warnings:string[]}
export interface GeneratedProject{stations:Station[];sections:DerivedSection[];errors:string[];warnings:string[];totalCapacityM3:number}

const uid=()=>`section-${crypto.randomUUID?.()??Math.random().toString(36).slice(2)}`;
const palette=["#35dfbd","#43aee8","#8a73e8","#f2b84b","#ef7d65"];
export function emptySection(index=0,previous?:OpenHoleSection):OpenHoleSection{return{id:uid(),name:`Open-hole section ${index+1}`,diameterMm:previous?.diameterMm??444.5,lengthM:index?300:500,path:index?"straight":"vertical",endInclination:index?previous?.endInclination??0:0,endAzimuth:index?previous?.endAzimuth??0:0,maxBuildRate:null,maxTurnRate:null,color:palette[index%palette.length],confirmed:false};}
export function createProject(unitSystem:UnitSystem="metric"):WellProject{const first=emptySection();return{version:1,name:"New open-hole well",classification:"Planned well",unitSystem,openHoleSections:[first],display:{selectedSectionId:first.id,labels:true,cameraDrift:true}};}
const rad=(v:number)=>v*Math.PI/180;
const angleDelta=(from:number,to:number)=>((to-from+540)%360)-180;
function nextStation(previous:Station,md:number,inclination:number,azimuth:number,sectionId:string):Station{const distance=md-previous.md,i1=rad(previous.inclination),i2=rad(inclination),a1=rad(previous.azimuth),a2=rad(azimuth),dogleg=Math.acos(Math.max(-1,Math.min(1,Math.cos(i2-i1)-Math.sin(i1)*Math.sin(i2)*(1-Math.cos(a2-a1))))),ratio=dogleg<1e-9?1:2/dogleg*Math.tan(dogleg/2);return{md,inclination,azimuth:(azimuth+360)%360,tvd:previous.tvd+distance/2*(Math.cos(i1)+Math.cos(i2))*ratio,northing:previous.northing+distance/2*(Math.sin(i1)*Math.cos(a1)+Math.sin(i2)*Math.cos(a2))*ratio,easting:previous.easting+distance/2*(Math.sin(i1)*Math.sin(a1)+Math.sin(i2)*Math.sin(a2))*ratio,sectionId};}
export function validateProject(project:WellProject):string[]{const errors:string[]=[];if(!project||project.version!==1||"wellbores"in(project as unknown as Record<string,unknown>))return["Unsupported FluidLab project schema."];if(!project.name?.trim())errors.push("Project name is required.");if(!["metric","imperial"].includes(project.unitSystem))errors.push("Choose project units.");if(!Array.isArray(project.openHoleSections)||!project.openHoleSections.length)errors.push("Add an open-hole section.");project.openHoleSections?.forEach((section,index)=>{const label=section.name||`Section ${index+1}`;if(!Number.isFinite(section.diameterMm)||section.diameterMm<=0)errors.push(`${label}: enter a positive hole diameter.`);if(!Number.isFinite(section.lengthM)||section.lengthM<=0)errors.push(`${label}: enter a positive drilled length.`);if(!["vertical","straight","curve"].includes(section.path))errors.push(`${label}: choose a valid path.`);if(section.path==="curve"&&(!Number.isFinite(section.endInclination)||section.endInclination!<0||section.endInclination!>180))errors.push(`${label}: ending inclination must be 0–180°.`);if(section.path==="curve"&&(!Number.isFinite(section.endAzimuth)||section.endAzimuth!<0||section.endAzimuth!>=360))errors.push(`${label}: ending azimuth must be 0–<360°.`);if(section.maxBuildRate!=null&&(!Number.isFinite(section.maxBuildRate)||section.maxBuildRate<0))errors.push(`${label}: maximum build rate cannot be negative.`);if(section.maxTurnRate!=null&&(!Number.isFinite(section.maxTurnRate)||section.maxTurnRate<0))errors.push(`${label}: maximum turn rate cannot be negative.`);});return[...new Set(errors)];}
export function generateProject(project:WellProject):GeneratedProject{const errors=validateProject(project),all:Station[]=[{md:0,tvd:0,northing:0,easting:0,inclination:0,azimuth:0}],derived:DerivedSection[]=[],warnings:string[]=[];let previous=all[0],totalCapacityM3=0;for(const section of project.openHoleSections??[]){if(!Number.isFinite(section.lengthM)||section.lengthM<=0)continue;const start={...previous},endInclination=section.path==="vertical"?0:section.path==="straight"?start.inclination:section.endInclination??start.inclination,endAzimuth=section.path==="curve"?section.endAzimuth??start.azimuth:start.azimuth,turn=angleDelta(start.azimuth,endAzimuth),count=Math.max(1,Math.ceil(section.lengthM/20)),stations:Station[]=[start];for(let index=1;index<=count;index++){const fraction=index/count,station=nextStation(previous,start.md+section.lengthM*fraction,start.inclination+(endInclination-start.inclination)*fraction,start.azimuth+turn*fraction,section.id);stations.push(station);all.push(station);previous=station;}const buildRate=(endInclination-start.inclination)/section.lengthM*30,turnRate=turn/section.lengthM*30,i1=rad(start.inclination),i2=rad(endInclination),dogleg=Math.acos(Math.max(-1,Math.min(1,Math.cos(i2-i1)-Math.sin(i1)*Math.sin(i2)*(1-Math.cos(rad(turn))))))*180/Math.PI,sectionWarnings:string[]=[];if(section.maxBuildRate!=null&&Math.abs(buildRate)>section.maxBuildRate)sectionWarnings.push(`${section.name}: calculated build rate exceeds its maximum.`);if(section.maxTurnRate!=null&&Math.abs(turnRate)>section.maxTurnRate)sectionWarnings.push(`${section.name}: calculated turn rate exceeds its maximum.`);warnings.push(...sectionWarnings);const capacityM3=Math.PI*(section.diameterMm/1000)**2/4*section.lengthM;totalCapacityM3+=capacityM3;derived.push({sectionId:section.id,start,end:previous,dogleg,buildRate,turnRate,capacityM3,stations,warnings:sectionWarnings});}return{stations:all,sections:derived,errors,warnings,totalCapacityM3};}
export function parseProjectJson(text:string):WellProject|null{if(new TextEncoder().encode(text).length>1024*1024)return null;try{const value=JSON.parse(text)as WellProject;return validateProject(value).length?null:value;}catch{return null;}}
export const projectFileName=(name:string)=>`${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"well"}.fluidlab.json`;
export const cubicMetresToBbl=(value:number)=>value*6.28981077;
