import { describe,expect,it } from "vitest";
import { calculateVolumes,createProject,emptyElement,generateProject,parseProjectJson,parseSurvey,trajectoryMd,validateProject } from "./engineering";

describe("section-based engineering model",()=>{
  it.each(["vertical","inclined-hold","build","drop","turn","compound","horizontal"] as const)("generates continuous %s geometry",type=>{const p=createProject(),segment=emptyElement(type);segment.length=300;p.wellbores[0].trajectory=[segment];p.wellbores[0].holes[0].endMd=300;const g=generateProject(p);expect(g.errors).toEqual([]);expect(g.stations[p.wellbores[0].id][0].md).toBe(0);expect(g.stations[p.wellbores[0].id].at(-1)!.md).toBeCloseTo(300);});
  it("appends a survey span and a child branch at its parent junction",()=>{const p=createProject(),root=p.wellbores[0];root.trajectory=[{...emptyElement("survey"),stations:parseSurvey("100,10,90\n200,20,90")}];root.holes[0].endMd=200;p.wellbores.push({id:"branch",name:"Branch",status:"planned",parent:{wellboreId:root.id,junctionMd:100},trajectory:[emptyElement("horizontal")],holes:[],tubulars:[],cement:[],color:"#ffffff",visible:true});const g=generateProject(p);expect(g.errors).toEqual([]);expect(g.stations[root.id].at(-1)!.md).toBe(200);expect(g.stations.branch[0].tvd).toBeCloseTo(g.stations[root.id].find(s=>s.md===100)!.tvd);});
  it("validates overlaps and impossible tubular dimensions",()=>{const p=createProject(),wb=p.wellbores[0];wb.holes.push({...wb.holes[0],id:"two",startMd:400,endMd:500});wb.tubulars.push({id:"c",name:"Casing",type:"casing",topMd:0,bottomMd:400,nominalMm:200,odMm:150,idMm:160,weightKgM:null,grade:"",status:"planned",color:"#fff000",visible:true});expect(validateProject(p).join(" ")).toMatch(/overlap|OD/);});
  it("calculates known cylindrical capacities and drillstring displacement",()=>{const p=createProject(),wb=p.wellbores[0];wb.holes=[{...wb.holes[0],diameterMm:200,endMd:100}];wb.trajectory=[{...emptyElement("vertical"),length:100}];p.operation.bitMd=100;p.drillStrings[0].components=[{id:"pipe",name:"Pipe",type:"drillpipe",length:100,odMm:100,idMm:80,maxOdMm:null}];const v=calculateVolumes(p);expect(v.openHole).toBeCloseTo(Math.PI*.2**2/4*100);expect(v.drillStringInternal).toBeCloseTo(Math.PI*.08**2/4*100);expect(v.pipeDisplacement).toBeCloseTo(Math.PI*(.1**2-.08**2)/4*100);});
  it("round trips only the new schema",()=>{const p=createProject("imperial");expect(parseProjectJson(JSON.stringify(p))).toEqual(p);expect(parseProjectJson(JSON.stringify({version:1,name:"legacy",type:"horizontal"}))).toBeNull();expect(trajectoryMd(p.wellbores[0])).toBe(500);});
});
