export type UnitSystem = "metric" | "imperial";
export type SegmentType = "vertical"|"inclined-hold"|"build"|"drop"|"turn"|"compound"|"horizontal"|"survey";
export interface SurveyStation { mdOffset:number; inclination:number; azimuth:number }
export interface TrajectoryElement { id:string; name:string; type:SegmentType; length:number; endInclination:number; endAzimuth:number; buildRate:number; turnRate:number; stations:SurveyStation[] }
export interface HoleInterval { id:string; name:string; startMd:number; endMd:number; diameterMm:number; underreamedDiameterMm:number|null; status:"planned"|"drilled"; color:string; visible:boolean }
export interface TubularString { id:string; name:string; type:"casing"|"liner"|"tieback"|"tubing"|"other"; topMd:number; bottomMd:number; nominalMm:number; odMm:number; idMm:number; weightKgM:number|null; grade:string; status:"planned"|"installed"; color:string; visible:boolean }
export interface CementPlacement { id:string; name:string; tubularId:string; topMd:number; bottomMd:number; excessPercent:number; material:string; status:"planned"|"actual"; color:string; visible:boolean }
export interface Wellbore { id:string; name:string; status:"planned"|"active"|"complete"; parent:{wellboreId:string;junctionMd:number}|null; trajectory:TrajectoryElement[]; holes:HoleInterval[]; tubulars:TubularString[]; cement:CementPlacement[]; color:string; visible:boolean }
export interface DrillComponent { id:string; name:string; type:"bit"|"bha"|"collar"|"heavyweight"|"drillpipe"|"sub"|"other"; length:number; odMm:number; idMm:number; maxOdMm:number|null }
export interface DrillStringConfiguration { id:string; name:string; components:DrillComponent[] }
export interface OperationalSnapshot { wellboreId:string; drillStringId:string|null; bitMd:number; timestamp:string; label:string }
export interface DisplaySettings { formations:boolean; labels:boolean; cameraDrift:boolean; mode:"overview"|"cutaway"; selectedKind:"wellbore"|"hole"|"tubular"|"cement"|"drillstring"; selectedId:string|null; clipTopMd:number|null; clipBottomMd:number|null }
export interface WellProject { version:1; name:string; classification:string; unitSystem:UnitSystem; wellbores:Wellbore[]; drillStrings:DrillStringConfiguration[]; operation:OperationalSnapshot; display:DisplaySettings }
export interface Station { md:number; inclination:number; azimuth:number; tvd:number; northing:number; easting:number; elementId?:string }
export interface GeneratedProject { stations:Record<string,Station[]>; errors:string[] }
export interface VolumeResult { openHole:number; tubularInternal:number; drillStringInternal:number; pipeDisplacement:number; annular:number; cementBase:number; cementWithExcess:number; aboveBit:number; belowBit:number; warnings:string[] }

const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID?.()??Math.random().toString(36).slice(2)}`;
const colors=["#35dfbd","#43aee8","#8a73e8","#f2b84b","#ef7d65"];
export const emptyElement=(type:SegmentType="vertical",index=0):TrajectoryElement=>({id:uid("segment"),name:`Segment ${index+1}`,type,length:type==="vertical"?500:300,endInclination:type==="horizontal"?90:type==="vertical"?0:30,endAzimuth:90,buildRate:3,turnRate:2,stations:[]});
export function createProject(unitSystem:UnitSystem="metric"):WellProject { const root="wellbore-root",ds="drillstring-main";return {version:1,name:"New well design",classification:"Exploration well",unitSystem,wellbores:[{id:root,name:"Main wellbore",status:"planned",parent:null,trajectory:[emptyElement("vertical",0)],holes:[{id:uid("hole"),name:"Surface hole",startMd:0,endMd:500,diameterMm:444.5,underreamedDiameterMm:null,status:"planned",color:colors[0],visible:true}],tubulars:[],cement:[],color:colors[0],visible:true}],drillStrings:[{id:ds,name:"Primary drillstring",components:[{id:uid("component"),name:"Bit",type:"bit",length:.3,odMm:215.9,idMm:0,maxOdMm:null},{id:uid("component"),name:"Drillpipe",type:"drillpipe",length:499.7,odMm:127,idMm:108.6,maxOdMm:168.3}]}],operation:{wellboreId:root,drillStringId:ds,bitMd:500,timestamp:new Date().toISOString(),label:"Planned drilling"},display:{formations:true,labels:true,cameraDrift:true,mode:"overview",selectedKind:"wellbore",selectedId:root,clipTopMd:null,clipBottomMd:null}}; }

const rad=(v:number)=>v*Math.PI/180;
function nextStation(previous:Station,md:number,inclination:number,azimuth:number):Station { const d=md-previous.md,i1=rad(previous.inclination),i2=rad(inclination),a1=rad(previous.azimuth),a2=rad(azimuth);const dog=Math.acos(Math.max(-1,Math.min(1,Math.cos(i2-i1)-Math.sin(i1)*Math.sin(i2)*(1-Math.cos(a2-a1)))));const rf=dog<1e-8?1:2/dog*Math.tan(dog/2);return {md,inclination,azimuth,tvd:previous.tvd+d/2*(Math.cos(i1)+Math.cos(i2))*rf,northing:previous.northing+d/2*(Math.sin(i1)*Math.cos(a1)+Math.sin(i2)*Math.cos(a2))*rf,easting:previous.easting+d/2*(Math.sin(i1)*Math.sin(a1)+Math.sin(i2)*Math.sin(a2))*rf}; }
export function interpolate(stations:Station[],md:number):Station { if(md<=stations[0].md)return {...stations[0],md};if(md>=stations.at(-1)!.md)return {...stations.at(-1)!};const i=stations.findIndex(s=>s.md>=md),a=stations[i-1],b=stations[i],t=(md-a.md)/(b.md-a.md);return {md,inclination:a.inclination+(b.inclination-a.inclination)*t,azimuth:a.azimuth+(b.azimuth-a.azimuth)*t,tvd:a.tvd+(b.tvd-a.tvd)*t,northing:a.northing+(b.northing-a.northing)*t,easting:a.easting+(b.easting-a.easting)*t}; }
function appendElement(stations:Station[],element:TrajectoryElement){const start=stations.at(-1)!;if(element.type==="survey"&&element.stations.length){for(const raw of element.stations.filter(s=>s.mdOffset>0).sort((a,b)=>a.mdOffset-b.mdOffset))stations.push({...nextStation(stations.at(-1)!,start.md+raw.mdOffset,raw.inclination,raw.azimuth),elementId:element.id});return;}const length=element.length,count=Math.max(1,Math.ceil(length/30)),startI=start.inclination,startA=start.azimuth;let endI=element.endInclination,endA=element.endAzimuth;if(element.type==="vertical")endI=0;if(element.type==="horizontal")endI=90;if(element.type==="inclined-hold"||element.type==="turn")endI=startI;if(["vertical","inclined-hold","horizontal","build","drop"].includes(element.type))endA=startA;for(let i=1;i<=count;i++){const t=i/count;stations.push({...nextStation(stations.at(-1)!,start.md+length*t,startI+(endI-startI)*t,startA+(endA-startA)*t),elementId:element.id});}}
export function generateProject(project:WellProject):GeneratedProject { const errors=validateProject(project),result:Record<string,Station[]>={};const pending=[...project.wellbores];let guard=0;while(pending.length&&guard++<project.wellbores.length*2){const wb=pending.shift()!;let first:Station;if(!wb.parent)first={md:0,inclination:0,azimuth:0,tvd:0,northing:0,easting:0};else{const parent=result[wb.parent.wellboreId];if(!parent){pending.push(wb);continue;}const tie=interpolate(parent,wb.parent.junctionMd);first={...tie,md:0};}const stations=[first];wb.trajectory.forEach(element=>appendElement(stations,element));result[wb.id]=stations;}return {stations:result,errors}; }
export function intervalStations(stations:Station[],start:number,end:number){return [interpolate(stations,start),...stations.filter(s=>s.md>start&&s.md<end),interpolate(stations,end)];}

export function validateProject(project:WellProject):string[]{const errors:string[]=[];if(project.version!==1)errors.push("Unsupported project schema.");if(!project.name.trim())errors.push("Project name is required.");if(!["metric","imperial"].includes(project.unitSystem))errors.push("Choose project units.");if(!project.wellbores.length)errors.push("Add a root wellbore.");const ids=new Set(project.wellbores.map(w=>w.id));if(project.wellbores.filter(w=>!w.parent).length!==1)errors.push("A project must have exactly one root wellbore.");for(const wb of project.wellbores){if(wb.parent&&!ids.has(wb.parent.wellboreId))errors.push(`${wb.name}: parent wellbore is missing.`);if(!wb.trajectory.length)errors.push(`${wb.name}: add a trajectory segment.`);wb.trajectory.forEach(s=>{if(s.type==="survey"?(s.stations.length<1||s.stations.some(p=>!Number.isFinite(p.mdOffset)||p.mdOffset<=0||p.inclination<0||p.inclination>180||p.azimuth<0||p.azimuth>=360)):(!Number.isFinite(s.length)||s.length<=0))errors.push(`${wb.name}/${s.name}: invalid trajectory values.`);});const total=trajectoryMd(wb);[...wb.holes,...wb.tubulars,...wb.cement].forEach(item=>{const start="startMd"in item?item.startMd:item.topMd,end="endMd"in item?item.endMd:item.bottomMd;if(start<0||end<=start||end>total+.01)errors.push(`${wb.name}/${item.name}: invalid MD range.`);});const sorted=[...wb.holes].sort((a,b)=>a.startMd-b.startMd);sorted.forEach((h,i)=>{if(h.diameterMm<=0)errors.push(`${h.name}: hole diameter must be positive.`);if(i&&h.startMd<sorted[i-1].endMd)errors.push(`${wb.name}: hole intervals overlap.`);});wb.tubulars.forEach(t=>{if(t.idMm<=0||t.odMm<=t.idMm)errors.push(`${t.name}: OD must exceed ID.`);});wb.cement.forEach(c=>{const t=wb.tubulars.find(x=>x.id===c.tubularId);if(!t||c.topMd<t.topMd||c.bottomMd>t.bottomMd)errors.push(`${c.name}: cement must lie on its tubular string.`);});}if(!ids.has(project.operation.wellboreId))errors.push("Active wellbore is missing.");return [...new Set(errors)];}
export const trajectoryMd=(wb:Wellbore)=>wb.trajectory.reduce((sum,s)=>sum+(s.type==="survey"?(s.stations.at(-1)?.mdOffset??0):s.length),0);
const area=(diameterMm:number)=>Math.PI*(diameterMm/1000)**2/4;
function holeAt(wb:Wellbore,md:number){return wb.holes.find(h=>md>=h.startMd&&md<=h.endMd);}
function enclosingArea(wb:Wellbore,md:number,exclude?:string){const tubulars=wb.tubulars.filter(t=>t.id!==exclude&&md>=t.topMd&&md<=t.bottomMd).sort((a,b)=>a.idMm-b.idMm);return tubulars.length?area(tubulars[0].idMm):area(holeAt(wb,md)?.underreamedDiameterMm??holeAt(wb,md)?.diameterMm??0);}
export function calculateVolumes(project:WellProject):VolumeResult {const wb=project.wellbores.find(w=>w.id===project.operation.wellboreId)??project.wellbores[0],warnings:string[]=[];let openHole=0,tubularInternal=0,annular=0,cementBase=0,cementWithExcess=0;wb.holes.forEach(h=>openHole+=area(h.underreamedDiameterMm??h.diameterMm)*(h.endMd-h.startMd));wb.tubulars.forEach(t=>tubularInternal+=area(t.idMm)*(t.bottomMd-t.topMd));const ds=project.drillStrings.find(d=>d.id===project.operation.drillStringId);let drillStringInternal=0,pipeDisplacement=0,cursor=project.operation.bitMd;if(ds)for(const c of ds.components){const inHole=Math.max(0,Math.min(c.length,cursor));drillStringInternal+=area(c.idMm)*inHole;pipeDisplacement+=(area(c.odMm)-area(c.idMm))*inHole;const mid=Math.max(0,cursor-inHole/2);const container=enclosingArea(wb,mid);if(container>area(c.odMm))annular+=(container-area(c.odMm))*inHole;else warnings.push(`${c.name} does not fit at ${Math.round(mid)} m MD.`);cursor-=inHole;}wb.cement.forEach(c=>{const t=wb.tubulars.find(x=>x.id===c.tubularId);if(!t)return;const base=Math.max(0,enclosingArea(wb,(c.topMd+c.bottomMd)/2,t.id)-area(t.odMm))*(c.bottomMd-c.topMd);cementBase+=base;cementWithExcess+=base*(1+c.excessPercent/100);});const total=openHole+tubularInternal,bit=Math.max(0,Math.min(project.operation.bitMd,trajectoryMd(wb)));return {openHole,tubularInternal,drillStringInternal,pipeDisplacement,annular,cementBase,cementWithExcess,aboveBit:total*(bit/Math.max(trajectoryMd(wb),1)),belowBit:total*(1-bit/Math.max(trajectoryMd(wb),1)),warnings};}
export const cubicMetresToBbl=(v:number)=>v*6.28981077;
export function parseProjectJson(text:string):WellProject|null{if(new TextEncoder().encode(text).length>1024*1024)return null;try{const value=JSON.parse(text) as WellProject;return validateProject(value).length?null:value;}catch{return null;}}
export const projectFileName=(name:string)=>`${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"well"}.fluidlab.json`;
export function parseSurvey(text:string):SurveyStation[]{const parsed=text.trim().split(/\r?\n/).map(line=>line.split(/[,\t]/).map(Number)).filter(row=>row.length>=3&&row.every(Number.isFinite)).map(([mdOffset,inclination,azimuth])=>({mdOffset,inclination,azimuth}));if(!parsed.length||parsed.some((p,i)=>p.mdOffset<=0||(i>0&&p.mdOffset<=parsed[i-1].mdOffset)||p.inclination<0||p.inclination>180||p.azimuth<0||p.azimuth>=360))throw new Error("Survey requires increasing MD offset, inclination 0–180°, and azimuth 0–359.99°.");return parsed;}
