/* eslint-disable react-hooks/set-state-in-effect,jsx-a11y/click-events-have-key-events,jsx-a11y/no-noninteractive-element-interactions */
import {lazy,Suspense,useCallback,useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {onAuthStateChanged,signOut,type User} from "firebase/auth";
import {useReducedMotion} from "motion/react";
import {FolderOpen,LogIn,LogOut,PanelLeftClose,PanelLeftOpen,Plus,RotateCcw,Save,Trash2} from "lucide-react";
import {auth,ensureFluidLabIdentity} from "../firebaseClient";
import {addIntermediateSection,createProject as createBlank,cubicMetresToBbl,deleteIntermediateSection,generateProject,type UnitSystem,type WellProject} from "./engineering";
import {createProject,getProject,updateProject} from "./projects";
import "./fluidlab.css";
const Scene=lazy(()=>import("./WellboreScene"));
const toLength=(m:number,u:UnitSystem)=>u==="metric"?m:m*3.280839895,fromLength=(v:number,u:UnitSystem)=>u==="metric"?v:v/3.280839895,toDiameter=(mm:number,u:UnitSystem)=>u==="metric"?mm:mm/25.4,fromDiameter=(v:number,u:UnitSystem)=>u==="metric"?v:v*25.4,lunit=(u:UnitSystem)=>u==="metric"?"m":"ft",dunit=(u:UnitSystem)=>u==="metric"?"mm":"in";
function Field({label,value,unit,onChange}:{label:string;value:number;unit:string;onChange:(value:number)=>void}){return <label className="number-field"><span>{label}</span><div><input type="number" value={Number.isInteger(value)?value:Number(value.toFixed(3))} min="0" step="0.1" onChange={event=>onChange(Number(event.target.value))}/><small>{unit}</small></div></label>}
function Modal({children}:{children:ReactNode}){return <div className="exit-overlay"><section className="exit-dialog" role="dialog" aria-modal="true">{children}</section></div>}
export default function FluidLab({onHome,onAuth,onDirtyChange,exitRequest,onConfirmBrowserExit}:{onHome:(section?:string)=>void;onAuth:(path:string)=>void;onDirtyChange:(dirty:boolean)=>void;exitRequest:number;onConfirmBrowserExit:()=>void}){
  const [design,setDesign]=useState(()=>createBlank()),[rendered,setRendered]=useState(()=>createBlank()),[projectId,setProjectId]=useState(()=>new URLSearchParams(location.search).get("project")),[revision,setRevision]=useState(0),[state,setState]=useState<"editing"|"saving"|"saved"|"failed"|"invalid">("editing"),[user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(false),[collapsed,setCollapsed]=useState(false),[view,setView]=useState<"perspective"|"profile">("perspective"),[reset,setReset]=useState(0),[visible,setVisible]=useState(!document.hidden),[notice,setNotice]=useState(""),[exitOpen,setExitOpen]=useState(false),[conflict,setConflict]=useState(false);
  const reduced=Boolean(useReducedMotion()),generated=useMemo(()=>generateProject(design),[design]),dirty=["editing","failed","invalid"].includes(state),account=Boolean(user&&!user.isAnonymous),units=design.unitSystem,saving=useRef(false);
  const edit=(recipe:(next:WellProject)=>void)=>{const next=structuredClone(design);recipe(next);setDesign(next);setState("editing")};
  useEffect(()=>onAuthStateChanged(auth,current=>{setUser(current);setAuthReady(true)}),[]);useEffect(()=>{void ensureFluidLabIdentity()},[]);
  useEffect(()=>{const change=()=>setVisible(!document.hidden);document.addEventListener("visibilitychange",change);return()=>document.removeEventListener("visibilitychange",change)},[]);
  useEffect(()=>onDirtyChange(dirty),[dirty,onDirtyChange]);useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};addEventListener("beforeunload",leave);return()=>removeEventListener("beforeunload",leave)},[dirty]);useEffect(()=>{if(exitRequest)setExitOpen(true)},[exitRequest]);
  useEffect(()=>{if(!projectId||!account)return;let active=true;void getProject(projectId).then(project=>{if(active){setDesign(project.design!);setRendered(project.design!);setRevision(project.revision);setState("saved")}}).catch(()=>{if(active){setNotice("This project could not be opened.");setProjectId(null)}});return()=>{active=false}},[projectId,account]);
  useEffect(()=>{if(!generated.errors.length)setRendered(design);else setState("invalid")},[design,generated.errors.length]);
  const save=useCallback(async()=>{if(generated.errors.length){setState("invalid");return}if(!account){onAuth(`/signin?returnTo=${encodeURIComponent(location.pathname+location.search)}`);return}if(saving.current)return;saving.current=true;setState("saving");try{if(projectId){const saved=await updateProject(projectId,design,revision,crypto.randomUUID());setRevision(saved.revision)}else{const saved=await createProject(design);setProjectId(saved.id);setRevision(saved.revision);history.replaceState({},"",`/fluidlab?project=${saved.id}`)}setState("saved")}catch(error){if(String((error as{code?:string}).code).includes("aborted"))setConflict(true);setState("failed")}finally{saving.current=false}},[account,design,generated.errors.length,onAuth,projectId,revision]);
  return <main className={`fluidlab-workspace ${collapsed?"panel-collapsed":""}`}><div className="workspace-scene"><Suspense fallback={<div className="scene-loading">Building conceptual profile…</div>}><Scene design={rendered} reducedMotion={reduced} active={visible} view={view} reset={reset} onContextLost={()=>setReset(value=>value+1)} onSelect={id=>edit(next=>next.display.selectedSectionId=id)}/></Suspense></div>
    <header className="workspace-topbar"><button className="workspace-brand" onClick={()=>dirty?setExitOpen(true):onHome()}><i/>Uniq<strong>Energy</strong><span>/ FluidLab</span></button><div className="workspace-title"><input value={design.name} onChange={event=>edit(next=>next.name=event.target.value)}/><small>Conceptual MD/TVD profile · single vertical plane</small></div><div className="workspace-status" aria-live="polite"><span className={state}>{state==="saving"?"Saving…":state==="saved"?"Saved to cloud":state==="invalid"?"Invalid changes":state==="failed"?"Save failed":"Editing in memory"}</span><button disabled={Boolean(generated.errors.length)} onClick={()=>void save()}><Save/> {account?"Save":"Sign in to save"}</button>{account&&<button onClick={()=>onAuth("/fluidlab/projects")}><FolderOpen/> Projects</button>}{authReady&&(account?<button title="Sign out" onClick={()=>void signOut(auth)}><LogOut/></button>:<button title="Sign in" onClick={()=>onAuth("/signin?returnTo=/fluidlab")}><LogIn/></button>)}</div></header>
    <aside className="workspace-panel survey-panel"><div className="panel-heading"><div><span>Conceptual well builder</span><strong>{design.sections.length} sections · MD/TVD endpoints</strong></div><button onClick={()=>setCollapsed(value=>!value)}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button></div><div className="panel-body editor-content"><div className="workflow-intro"><b>Define section endpoints</b><p>Enter cumulative MD, cumulative TVD, and bit size. FluidLab infers a smooth single-plane profile; it is not a directional survey.</p></div><label className="text-field"><span>Units</span><select value={units} onChange={event=>edit(next=>next.unitSystem=event.target.value as UnitSystem)}><option value="metric">Metric</option><option value="imperial">Imperial</option></select></label>
      {design.sections.map((section,index)=>{const derived=generated.sections[index],startMd=index?design.sections[index-1].endMdM:0,startTvd=index?design.sections[index-1].endTvdM:0;return <fieldset className={`design-card ${design.display.selectedSectionId===section.id?"selected":""}`} key={section.id} onClick={()=>edit(next=>next.display.selectedSectionId=section.id)}><legend><span>{index+1}</span><input value={section.name} onChange={event=>edit(next=>next.sections[index].name=event.target.value)}/>{section.category==="intermediate"&&<button aria-label={`Delete ${section.name}`} onClick={event=>{event.stopPropagation();edit(next=>deleteIntermediateSection(next,section.id))}}><Trash2/></button>}</legend><small className="section-kind">{section.category}</small><div className="control-grid"><Field label="End MD" value={toLength(section.endMdM,units)} unit={lunit(units)} onChange={value=>edit(next=>next.sections[index].endMdM=fromLength(value,units))}/><Field label="End TVD" value={toLength(section.endTvdM,units)} unit={lunit(units)} onChange={value=>edit(next=>next.sections[index].endTvdM=fromLength(value,units))}/><Field label="Bit size" value={toDiameter(section.diameterMm,units)} unit={dunit(units)} onChange={value=>edit(next=>next.sections[index].diameterMm=fromDiameter(value,units))}/></div><div className="section-summary"><span>ΔMD {toLength(section.endMdM-startMd,units).toFixed(1)} · ΔTVD {toLength(section.endTvdM-startTvd,units).toFixed(1)} {lunit(units)}</span>{derived&&<><span>Horizontal {toLength(derived.horizontalDisplacementM,units).toFixed(1)} {lunit(units)}</span><strong>{units==="metric"?`${derived.capacityM3.toFixed(2)} m³`:`${cubicMetresToBbl(derived.capacityM3).toFixed(2)} bbl`}</strong></>}</div></fieldset>})}
      <button className="add-row" onClick={()=>edit(next=>{const id=addIntermediateSection(next);next.display.selectedSectionId=id})}><Plus/> Add Intermediate section</button><section className="total-capacity"><span>Total MD</span><strong>{toLength(design.sections.at(-1)?.endMdM??0,units).toFixed(1)} {lunit(units)}</strong><span>Total TVD</span><strong>{toLength(design.sections.at(-1)?.endTvdM??0,units).toFixed(1)} {lunit(units)}</strong><span>Horizontal displacement</span><strong>{toLength(generated.totalHorizontalM,units).toFixed(1)} {lunit(units)}</strong><span>Open-hole capacity</span><strong>{units==="metric"?`${generated.totalCapacityM3.toFixed(2)} m³`:`${cubicMetresToBbl(generated.totalCapacityM3).toFixed(2)} bbl`}</strong></section>{generated.errors.length>0&&<div className="validation-box" role="alert"><b>Profile paused at the last valid design</b><ul>{generated.errors.map(error=><li key={error}>{error}</li>)}</ul></div>}<p className="concept-disclaimer">Conceptual visualization only. MD/TVD endpoints do not define a survey-accurate trajectory.</p></div></aside>
    <div className="camera-toolbar"><button className={view==="perspective"?"active":""} onClick={()=>setView("perspective")}>Perspective</button><button className={view==="profile"?"active":""} onClick={()=>setView("profile")}>Profile</button><button title="Reset camera" onClick={()=>setReset(value=>value+1)}><RotateCcw/></button></div>{notice&&<button className="workspace-notice" onClick={()=>setNotice("")}>{notice}</button>}
    {exitOpen&&<Modal><h2>Leave this design?</h2><p>Unsaved in-memory changes will be lost.</p><div><button onClick={()=>setExitOpen(false)}>Keep editing</button><button className="danger" onClick={()=>{onDirtyChange(false);if(exitRequest)onConfirmBrowserExit();else onHome()}}>Leave without saving</button></div></Modal>}{conflict&&<Modal><h2>Newer cloud changes exist</h2><p>Open the saved project again before making more changes.</p><div><button onClick={()=>setConflict(false)}>Keep this screen</button><button onClick={()=>location.reload()}>Reload project</button></div></Modal>}
  </main>}
