import { useEffect, useMemo, useState } from "react";
import { Archive, Copy, FolderOpen, Search, Trash2 } from "lucide-react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../firebaseClient";
import { listProjects, projectAction, type Project } from "./projects";
import "./projects.css";

export default function ProjectLibrary({ navigate }:{navigate:(path:string)=>void}) {
  const [projects,setProjects]=useState<Project[]>([]),[archived,setArchived]=useState(false),[query,setQuery]=useState(""),[sort,setSort]=useState<"updated"|"name">("updated"),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  useEffect(()=>onAuthStateChanged(auth,user=>{if(!user||user.isAnonymous)navigate("/signin?returnTo=/fluidlab/projects");}),[navigate]);
  const load=async()=>{setLoading(true);setError("");try{setProjects(await listProjects(archived));}catch{setError("Projects could not be loaded. Sign in and try again.");}finally{setLoading(false);}};
  useEffect(()=>{let active=true;void listProjects(archived).then(items=>{if(active)setProjects(items);}).catch(()=>{if(active)setError("Projects could not be loaded. Sign in and try again.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[archived]);
  const shown=useMemo(()=>projects.filter(project=>project.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):b.updatedAt.localeCompare(a.updatedAt)),[projects,query,sort]);
  const act=async(action:"duplicate"|"archive"|"restore"|"delete",project:Project)=>{if(action==="delete"&&!confirm(`Permanently delete “${project.name}” and all its versions?`))return;try{await projectAction(action,project.id);await load();}catch{setError("That project action could not be completed.");}};
  return <main className="project-library"><header><button className="library-brand" onClick={()=>navigate("/fluidlab")}><i/>Uniq<strong>Energy</strong> / FluidLab</button><button onClick={()=>navigate("/fluidlab")}>New design</button></header><section><div className="library-heading"><div><span>Engineering workspace</span><h1>{archived?"Archived projects":"My projects"}</h1><p>Open a live draft or manage your FluidLab project files.</p></div><button onClick={()=>setArchived(!archived)}><Archive/> {archived?"Active projects":"View archive"}</button></div><div className="library-tools"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search projects"/></label><select value={sort} onChange={event=>setSort(event.target.value as "updated"|"name")}><option value="updated">Recently updated</option><option value="name">Project name</option></select></div>{error&&<p className="library-error">{error}</p>}{loading?<p className="library-empty">Loading projects…</p>:shown.length===0?<p className="library-empty">{query?"No matching projects.":archived?"No archived projects.":"No cloud projects yet. Start a design and save it here."}</p>:<div className="project-grid">{shown.map(project=><article key={project.id}><button className="project-open" onClick={()=>navigate(`/fluidlab?project=${project.id}`)}><FolderOpen/><span><strong>{project.name}</strong><small>Updated {new Date(project.updatedAt).toLocaleString()} · revision {project.revision}</small></span></button><div><button title="Duplicate" onClick={()=>void act("duplicate",project)}><Copy/></button><button title={archived?"Restore":"Archive"} onClick={()=>void act(archived?"restore":"archive",project)}><Archive/></button><button title="Delete permanently" onClick={()=>void act("delete",project)}><Trash2/></button></div></article>)}</div>}</section></main>;
}
