/* eslint-disable react/no-unknown-property,react-hooks/immutability,react-hooks/preserve-manual-memoization */
import {useEffect,useMemo} from "react";
import {Canvas,useThree} from "@react-three/fiber";
import {Grid,Html,Line,OrbitControls} from "@react-three/drei";
import * as THREE from "three";
import {generateProject,type DerivedSection,type WellProject,type WellSection} from "./engineering";
const point=(item:{horizontalM:number;tvdM:number})=>new THREE.Vector3(item.horizontalM,-item.tvdM,0);
function Camera({points,view,reset}:{points:THREE.Vector3[];view:"perspective"|"profile";reset:number}){const{camera,controls}=useThree();useEffect(()=>{if(!points.length)return;const box=new THREE.Box3().setFromPoints(points),center=box.getCenter(new THREE.Vector3()),size=Math.max(box.getSize(new THREE.Vector3()).length(),100),direction=view==="profile"?new THREE.Vector3(0,0,1):new THREE.Vector3(1,.45,1);camera.position.copy(center.clone().add(direction.normalize().multiplyScalar(size*.9)));camera.near=.1;camera.far=size*12;camera.updateProjectionMatrix();if(controls&&"target"in controls){const target=controls as unknown as{target:THREE.Vector3;update:()=>void};target.target.copy(center);target.update()}},[camera,controls,points,view,reset]);return null}
function Tube({section,derived,selected,onSelect}:{section:WellSection;derived:DerivedSection;selected:boolean;onSelect:(id:string)=>void}){const points=derived.points.map(point),curve=useMemo(()=>new THREE.CatmullRomCurve3(points),[points]),geometry=useMemo(()=>new THREE.TubeGeometry(curve,Math.max(24,points.length),Math.max(1.2,section.diameterMm/55),14,false),[curve,points.length,section.diameterMm]);if(!section.visible)return null;return <group><mesh geometry={geometry} onClick={event=>{event.stopPropagation();onSelect(section.id)}}><meshStandardMaterial color={section.color} transparent opacity={selected?1:.76} emissive={section.color} emissiveIntensity={selected?.28:.05}/></mesh>{selected&&<Line points={points} color="#fff" lineWidth={1}/>}<group position={point(derived.points.at(-1)!)}><mesh><sphereGeometry args={[5,12,12]}/><meshStandardMaterial color={selected?"#fff":"#f2b84b"}/></mesh><Html center distanceFactor={260}><span className="scene-label">{section.name} · MD {section.endMdM.toFixed(0)} · TVD {section.endTvdM.toFixed(0)}</span></Html></group></group>}
export default function WellboreScene({design,reducedMotion,active,view,reset,onContextLost,onSelect}:{design:WellProject;reducedMotion:boolean;active:boolean;view:"perspective"|"profile";reset:number;onContextLost:()=>void;onSelect:(id:string)=>void}){const model=useMemo(()=>generateProject(design),[design]),points=useMemo(()=>model.points.map(point),[model.points]);return <Canvas frameloop={active?"always":"demand"} gl={{antialias:true,alpha:false}} camera={{fov:42}} onCreated={({gl})=>gl.domElement.addEventListener("webglcontextlost",event=>{event.preventDefault();onContextLost()},{once:true})}><color attach="background" args={["#03131d"]}/><ambientLight intensity={1.25}/><directionalLight position={[800,500,600]} intensity={2}/><Grid args={[10000,10000]} cellSize={100} sectionSize={500} fadeDistance={7000} cellColor="#0c5660" sectionColor="#16818b"/>{design.sections.map((section,index)=>model.sections[index]&&<Tube key={section.id} section={section} derived={model.sections[index]} selected={design.display.selectedSectionId===section.id} onSelect={onSelect}/>) }<OrbitControls makeDefault enableDamping={!reducedMotion}/><Camera points={points} view={view} reset={reset}/></Canvas>}
