/* eslint-disable react/no-unknown-property */
import { Html,OrbitControls,PerspectiveCamera } from "@react-three/drei";
import { Canvas,useFrame,useThree } from "@react-three/fiber";
import { useEffect,useMemo,useRef } from "react";
import * as THREE from "three";
import { generateProject,intervalStations,interpolate,type Station,type WellProject } from "./engineering";
export type CameraView="overview"|"side"|"top"|"target";
type Props={design:WellProject;reducedMotion:boolean;lowPower:boolean;active:boolean;view:CameraView;reset:number;onCanvas:(canvas:HTMLCanvasElement|null)=>void;onSelect?:(kind:WellProject["display"]["selectedKind"],id:string)=>void;onContextLost?:()=>void};
function Tube({points,radius,color,opacity=.72,selected=false,onClick}:{points:THREE.Vector3[];radius:number;color:string;opacity?:number;selected?:boolean;onClick?:()=>void}){if(points.length<2)return null;const curve=new THREE.CatmullRomCurve3(points);return <mesh onClick={event=>{event.stopPropagation();onClick?.();}}><tubeGeometry args={[curve,Math.max(12,points.length*2),radius,14,false]}/><meshStandardMaterial color={color} transparent opacity={opacity} roughness={.3} metalness={selected?.55:.2} emissive={selected?color:"#000000"} emissiveIntensity={selected?.24:0} depthWrite={opacity>.8}/></mesh>}
function Camera({view,reset,target,cutaway,reduced}:{view:CameraView;reset:number;target:THREE.Vector3;cutaway:boolean;reduced:boolean}){const controls=useRef<React.ElementRef<typeof OrbitControls>>(null),camera=useThree(s=>s.camera);useEffect(()=>{const positions:Record<CameraView,THREE.Vector3>={overview:new THREE.Vector3(11,7,12),side:new THREE.Vector3(13,0,.5),top:new THREE.Vector3(.1,16,.1),target:new THREE.Vector3(8,-4,8)};camera.position.copy(cutaway?new THREE.Vector3(target.x+3,target.y+1,target.z+3):positions[view]);camera.lookAt(target);controls.current?.target.copy(target);controls.current?.update();},[camera,view,reset,target,cutaway]);return <OrbitControls ref={controls} enablePan minDistance={cutaway?1:4} maxDistance={30} autoRotate={!reduced&&!cutaway&&view==="overview"} autoRotateSpeed={.16}/>}
function Grid(){const grid=useRef<THREE.GridHelper>(null);useFrame(({camera},d)=>{if(!grid.current)return;const mats=Array.isArray(grid.current.material)?grid.current.material:[grid.current.material];mats.forEach(m=>{m.transparent=true;m.opacity=THREE.MathUtils.damp(m.opacity,THREE.MathUtils.smoothstep(camera.position.y,2,5)*.42,8,d);});});return <gridHelper ref={grid} args={[18,18,"#236170","#103642"]} position={[0,3.05,0]}/>}
function Scene({design,reducedMotion,view,reset,onSelect}:Pick<Props,"design"|"reducedMotion"|"view"|"reset"|"onSelect">){const generated=useMemo(()=>generateProject(design),[design]),all=Object.values(generated.stations).flat();const bounds=useMemo(()=>{const min={e:Math.min(...all.map(p=>p.easting)),n:Math.min(...all.map(p=>p.northing)),y:Math.min(...all.map(p=>-p.tvd))},max={e:Math.max(...all.map(p=>p.easting)),n:Math.max(...all.map(p=>p.northing)),y:Math.max(...all.map(p=>-p.tvd))},center=new THREE.Vector3((min.e+max.e)/2,(min.y+max.y)/2,-(min.n+max.n)/2),scale=9/Math.max(max.e-min.e,max.n-min.n,max.y-min.y,100);return {center,scale};},[all]);const point=(s:Station)=>new THREE.Vector3(s.easting,-s.tvd,-s.northing).sub(bounds.center).multiplyScalar(bounds.scale);const cut=design.display.mode==="cutaway";let target=new THREE.Vector3();if(cut&&design.display.selectedId){for(const wb of design.wellbores){const s=generated.stations[wb.id];const item=[...wb.holes,...wb.tubulars,...wb.cement].find(x=>x.id===design.display.selectedId);if(item&&s){const start="startMd"in item?item.startMd:item.topMd,end="endMd"in item?item.endMd:item.bottomMd;target=point(interpolate(s,(start+end)/2));}}}
return <><PerspectiveCamera makeDefault position={[11,7,12]} fov={42}/><ambientLight intensity={1.15}/><directionalLight position={[8,12,10]} intensity={2.6}/><pointLight position={[0,-2,3]} intensity={14} distance={18} color="#1fdab8"/>{design.display.formations&&!cut&&[-4,-2,0,2].map(y=><mesh key={y} position={[0,y,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[15,13]}/><meshStandardMaterial color="#20404a" transparent opacity={.12} depthWrite={false}/></mesh>)}<Grid/>{design.wellbores.filter(w=>w.visible).map(wb=>{const stations=generated.stations[wb.id]??[];return <group key={wb.id}>{wb.holes.filter(h=>h.visible).map(h=><Tube key={h.id} points={intervalStations(stations,h.startMd,h.endMd).map(point)} radius={cut?.24:.07+Math.sqrt(h.diameterMm/450)*.08} color={h.color} opacity={cut?.18:.58} selected={design.display.selectedId===h.id} onClick={()=>onSelect?.("hole",h.id)}/>)}{wb.tubulars.filter(t=>t.visible).map(t=><Tube key={t.id} points={intervalStations(stations,t.topMd,t.bottomMd).map(point)} radius={cut?.15:.045+Math.sqrt(t.odMm/450)*.06} color={t.color} opacity={cut?.52:.85} selected={design.display.selectedId===t.id} onClick={()=>onSelect?.("tubular",t.id)}/>)}{wb.cement.filter(c=>c.visible).map(c=><Tube key={c.id} points={intervalStations(stations,c.topMd,c.bottomMd).map(point)} radius={cut?.195:.065} color={c.color} opacity={.28} selected={design.display.selectedId===c.id} onClick={()=>onSelect?.("cement",c.id)}/>)}{!wb.holes.length&&<Tube points={stations.map(point)} radius={.065} color={wb.color} onClick={()=>onSelect?.("wellbore",wb.id)}/>} {design.display.labels&&stations.length>0&&<group position={point(stations.at(-1)!)}><Html center><span className="scene-label">{wb.name} · {Math.round(stations.at(-1)!.md)} m MD</span></Html></group>}</group>})}{design.operation.drillStringId&&(()=>{const wb=design.wellbores.find(w=>w.id===design.operation.wellboreId),s=wb&&generated.stations[wb.id];return s?<Tube points={intervalStations(s,0,Math.min(design.operation.bitMd,s.at(-1)!.md)).map(point)} radius={cut?.07:.025} color="#f2b84b" opacity={.95} selected={design.display.selectedKind==="drillstring"} onClick={()=>onSelect?.("drillstring",design.operation.drillStringId!)}/>:null;})()}<Camera view={view} reset={reset} target={target} cutaway={cut} reduced={reducedMotion||!design.display.cameraDrift}/></>}
export default function WellboreScene(props:Props){return <Canvas key={`scene-${props.reset}`} dpr={props.lowPower?1:[1,1.6]} frameloop={props.active?"always":"never"} gl={{antialias:!props.lowPower,alpha:true,preserveDrawingBuffer:true,powerPreference:"high-performance"}} onCreated={({gl})=>{props.onCanvas(gl.domElement);gl.domElement.addEventListener("webglcontextlost",event=>{event.preventDefault();props.onContextLost?.();},{once:true});}}><color attach="background" args={["#061923"]}/><fog attach="fog" args={["#061923",18,34]}/><Scene {...props}/></Canvas>}
