/* eslint-disable react/no-unknown-property,react-hooks/immutability,react-hooks/preserve-manual-memoization */
import{useEffect,useMemo}from"react";
import{Canvas,useThree}from"@react-three/fiber";
import{Grid,Html,Line,OrbitControls}from"@react-three/drei";
import*as THREE from"three";
import{generateProject,type DerivedSection,type WellProject}from"./engineering";

const point=(s:{easting:number;tvd:number;northing:number})=>new THREE.Vector3(s.easting,-s.tvd,s.northing);
function Camera({points,view,reset}:{points:THREE.Vector3[];view:string;reset:number}){const{camera,controls}=useThree();useEffect(()=>{if(!points.length)return;const box=new THREE.Box3().setFromPoints(points),center=box.getCenter(new THREE.Vector3()),size=Math.max(box.getSize(new THREE.Vector3()).length(),100),direction=view==="top"?new THREE.Vector3(0,1,.001):view==="side"?new THREE.Vector3(1,.2,.001):new THREE.Vector3(1,.7,1);camera.position.copy(center.clone().add(direction.normalize().multiplyScalar(size*.9)));camera.near=.1;camera.far=size*10;camera.updateProjectionMatrix();if(controls&&"target"in controls){(controls as THREE.EventDispatcher&{target:THREE.Vector3;update:()=>void}).target.copy(center);(controls as THREE.EventDispatcher&{target:THREE.Vector3;update:()=>void}).update();}},[camera,controls,points,view,reset]);return null;}
function SectionTube({section,model,selected,onSelect}:{section:WellProject["openHoleSections"][number];model:DerivedSection;selected:boolean;onSelect:(id:string)=>void}){const points=model.stations.map(point),curve=useMemo(()=>new THREE.CatmullRomCurve3(points),[points]),radius=Math.max(1.2,section.diameterMm/55),geometry=useMemo(()=>new THREE.TubeGeometry(curve,Math.max(8,points.length*3),radius,12,false),[curve,points.length,radius]);return<group><mesh geometry={geometry} onClick={event=>{event.stopPropagation();onSelect(section.id)}}><meshStandardMaterial color={section.color} transparent opacity={selected?1:.76} emissive={section.color} emissiveIntensity={selected?.3:.06} roughness={.32}/></mesh>{selected&&<Line points={points} color="#ffffff" lineWidth={1}/>}<Html position={point(model.end)} center distanceFactor={260}><span className="scene-label">{section.name} · {model.end.md.toFixed(0)} m MD</span></Html></group>}
export default function WellboreScene({design,reducedMotion,active,view,reset,onCanvas,onContextLost,onSelect}:{design:WellProject;reducedMotion:boolean;lowPower:boolean;active:boolean;view:"overview"|"side"|"top"|"target";reset:number;onCanvas:(canvas:HTMLCanvasElement)=>void;onContextLost:()=>void;onSelect:(kind:"section",id:string)=>void}){const generated=useMemo(()=>generateProject(design),[design]),points=useMemo(()=>generated.stations.map(point),[generated.stations]);return<Canvas frameloop={active?"always":"demand"} gl={{antialias:true,alpha:false}} camera={{fov:42}} onCreated={({gl})=>{onCanvas(gl.domElement);gl.domElement.addEventListener("webglcontextlost",event=>{event.preventDefault();onContextLost();},{once:true});}}><color attach="background" args={["#03131d"]}/><ambientLight intensity={1.25}/><directionalLight position={[800,500,600]} intensity={2}/><Grid args={[10000,10000]} cellSize={100} sectionSize={500} fadeDistance={7000} cellColor="#0c5660" sectionColor="#16818b" position={[0,0,0]}/>{design.openHoleSections.map((section,index)=>generated.sections[index]&&<SectionTube key={section.id} section={section} model={generated.sections[index]} selected={design.display.selectedSectionId===section.id} onSelect={id=>onSelect("section",id)}/>)}<OrbitControls makeDefault enableDamping={!reducedMotion}/><Camera points={points} view={view} reset={reset}/></Canvas>}
