import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { onCall, HttpsError } from "firebase-functions/v2/https";
import { normalizeMiniApps, requireAdmin } from "../../core/auth.js";
import { callable } from "../../core/config.js";
import { auth } from "../../core/firebase.js";
import { email, role, text } from "../../core/values.js";
import { EMAIL_SECRETS, sendInvitationEmail } from "../../services/email.js";
import { INVITE_TTL_MS, invitationId, invitations, invitationToken, inviteUrl, publicInvitation, tokenHash } from "./helpers.js";
export const adminInviteUser = onCall({ ...callable, secrets: EMAIL_SECRETS }, async (request) => { const admin = await requireAdmin(request), address = email(request.data?.email), firstName = text(request.data?.firstName, "first name", 80), lastName = text(request.data?.lastName, "last name", 80), selectedRole = role(request.data?.role), enabledMiniApps = selectedRole === "admin" ? ["fluidlab", "pason-viewer"] : normalizeMiniApps(request.data?.enabledMiniApps); try { await auth.getUserByEmail(address); throw new HttpsError("already-exists", "A user already exists for this email."); } catch (error) { if (error instanceof HttpsError) throw error; if (error.code !== "auth/user-not-found") throw error; } const duplicate = await invitations().where("email", "==", address).where("status", "==", "pending").limit(1).get(); if (!duplicate.empty) throw new HttpsError("already-exists", "A pending invitation already exists for this email."); const id = invitationId(), token = invitationToken(), ref = invitations().doc(id), now = FieldValue.serverTimestamp(), data = { schemaVersion: 1, email: address, firstName, lastName, role: selectedRole, enabledMiniApps, status: "pending", tokenHash: tokenHash(token), expiresAt: Timestamp.fromMillis(Date.now() + INVITE_TTL_MS), createdAt: now, updatedAt: now, createdBy: admin.uid, updatedBy: admin.uid }; await ref.set(data); try { await sendInvitationEmail({ to: address, name: firstName, inviteUrl: inviteUrl(token) }); } catch { await ref.delete(); throw new HttpsError("unavailable", "The invitation email could not be sent."); } return { invitation: publicInvitation(id, (await ref.get()).data()) }; });
