/* eslint-disable jsx-a11y/no-static-element-interactions */
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { onAuthStateChanged, signOut, type User } from "firebase/auth";
import { Box, BrainCircuit, FolderOpen, LogOut, Search, Trash2, UserRound, X } from "lucide-react";
import { auth } from "../firebaseClient";
import { createFluidLabProject, createFluidProgramsProject, deleteProject, getAccount, listProjects, updateAccount, type AccountProfile, type Project } from "../fluidlab/projects";
import "./account.css";

function ProjectNameDialog({ busy, error, onCancel, onCreate }: { busy: boolean; error: string; onCancel: () => void; onCreate: (name: string) => void }) {
  const [name, setName] = useState(""), input = useRef<HTMLInputElement>(null), dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { input.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !busy) onCancel(); if (event.key === "Tab" && dialog.current) { const items = [...dialog.current.querySelectorAll<HTMLElement>("button,input")].filter((item) => !item.hasAttribute("disabled")); if (!items.length) return; const first = items[0], last = items.at(-1)!; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [busy, onCancel]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (name.trim()) onCreate(name.trim()); };
  return <div className="account-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onCancel(); }}><div ref={dialog} className="account-modal" role="dialog" aria-modal="true" aria-labelledby="new-project-title"><button className="account-modal-close" aria-label="Close" disabled={busy} onClick={onCancel}><X/></button><span>New FluidLab project</span><h2 id="new-project-title">Name your project</h2><p>Create a clear name so you can find this well design later.</p><form onSubmit={submit}><label>Project name<input ref={input} required maxLength={100} value={name} onChange={(event) => setName(event.target.value)} placeholder="Example: Clearwater 04-12"/></label>{error && <div className="account-error" role="alert">{error}</div>}<div><button type="button" disabled={busy} onClick={onCancel}>Cancel</button><button className="account-primary" disabled={busy || !name.trim()}>{busy ? "Creating…" : "Create project"}</button></div></form></div></div>;
}

export default function AccountPortal({ page, navigate }: { page: "projects" | "profile"; navigate: (path: string) => void }) {
  const [user, setUser] = useState<User | null>(null), [account, setAccount] = useState<AccountProfile | null>(null), [projects, setProjects] = useState<Project[]>([]), [loading, setLoading] = useState(true), [working, setWorking] = useState<"fluidlab" | "fluid-programs" | "profile" | null>(null), [nameOpen, setNameOpen] = useState(false), [modalError, setModalError] = useState(""), [error, setError] = useState(""), [query, setQuery] = useState(""), [firstName, setFirstName] = useState(""), [lastName, setLastName] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const profile = await getAccount(); setAccount(profile); setFirstName(profile.firstName); setLastName(profile.lastName); if (page === "projects") setProjects(await listProjects()); } catch (requestError) { const code = String((requestError as { code?: string }).code || ""); if (code.includes("failed-precondition") || code.includes("not-found")) navigate(`/signup?complete=1&email=${encodeURIComponent(auth.currentUser?.email || "")}`); else setError("Your account could not be loaded. Please try again."); } finally { setLoading(false); } }, [navigate, page]);
  useEffect(() => onAuthStateChanged(auth, (current) => { if (!current) { navigate(`/signin?returnTo=${encodeURIComponent(location.pathname)}`); return; } setUser(current); void load(); }), [load, navigate]);
  const shown = useMemo(() => projects.filter((project) => project.name.toLowerCase().includes(query.toLowerCase())), [projects, query]);
  const createFluidLab = async (name: string) => { setWorking("fluidlab"); setModalError(""); try { const project = await createFluidLabProject(name); navigate(`/account/projects/${project.id}/fluidlab`); } catch { setModalError("The FluidLab project could not be created. Try again."); } finally { setWorking(null); } };
  const createPrograms = async () => { setWorking("fluid-programs"); setError(""); try { const date = new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date()), project = await createFluidProgramsProject(`Fluid Programs · ${date}`); navigate(`/account/projects/${project.id}/fluid-programs`); } catch { setError("The Fluid Programs project could not be created."); } finally { setWorking(null); } };
  const remove = async (project: Project) => { if (!confirm(`Permanently delete “${project.name}”?`)) return; try { await deleteProject(project.id); setProjects((items) => items.filter((item) => item.id !== project.id)); } catch { setError("The project could not be deleted."); } };
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); setWorking("profile"); setError(""); try { const profile = await updateAccount(firstName, lastName); setAccount(profile); } catch { setError("Your profile could not be updated."); } finally { setWorking(null); } };
  const openProject = (project: Project) => navigate(`/account/projects/${project.id}/${project.type}`);
  return <main className="account-shell"><header><button className="account-brand" onClick={() => navigate("/")}><i/>Uniq<strong>Energy</strong><span>/ Account</span></button><nav><button className={page === "projects" ? "active" : ""} onClick={() => navigate("/account")}><FolderOpen/> Projects</button><button className={page === "profile" ? "active" : ""} onClick={() => navigate("/account/profile")}><UserRound/> Profile</button></nav></header>
    <section className="account-content">{error && <p className="account-error">{error}</p>}{loading ? <p className="account-empty">Loading your account…</p> : page === "profile" ? <form className="profile-card" onSubmit={saveProfile}><span>Account profile</span><h1>{account?.firstName} {account?.lastName}</h1><label>First name<input required maxLength={60} value={firstName} onChange={(event) => setFirstName(event.target.value)}/></label><label>Last name<input required maxLength={60} value={lastName} onChange={(event) => setLastName(event.target.value)}/></label><label>Email<input readOnly value={user?.email || account?.email || ""}/><small>Your login email cannot be changed here.</small></label><div className="profile-status">Status <b>{account?.status}</b></div><button className="account-primary" disabled={working === "profile"}>{working === "profile" ? "Saving…" : "Save profile"}</button><button type="button" className="account-logout" onClick={() => void signOut(auth).then(() => navigate("/signin"))}><LogOut/> Sign out</button></form> : <><div className="account-heading"><span>UniqEnergy applications</span><h1>Projects</h1><p>Create and manage every project connected to your account.</p></div><section className="app-section"><h2>Available apps</h2><div className="app-grid"><button className="app-card" disabled={working !== null} onClick={() => { setModalError(""); setNameOpen(true); }}><Box/><span><b>FluidLab</b><small>Build conceptual MD-only well profiles in 3D.</small></span><em>New project →</em></button><button className="app-card programs" disabled={working !== null} onClick={() => void createPrograms()}><BrainCircuit/><span><b>Fluid Programs</b><small>Chat with a drilling-fluids educational assistant.</small></span><em>{working === "fluid-programs" ? "Creating…" : "New conversation →"}</em></button></div></section><section className="saved-projects"><div><h2>Recent projects</h2><label><Search/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search projects"/></label></div>{shown.length ? <div className="account-project-grid">{shown.map((project) => <article key={project.id}><button onClick={() => openProject(project)}><FolderOpen/><span><b>{project.name}</b><small>{project.type === "fluidlab" ? "FluidLab" : "Fluid Programs"} · Autosaved {new Date(project.updatedAt).toLocaleString()}</small></span></button><button title="Delete project permanently" aria-label={`Delete ${project.name}`} onClick={() => void remove(project)}><Trash2/></button></article>)}</div> : <p className="account-empty">{query ? "No matching projects." : "No projects yet. Choose an application above to begin."}</p>}</section></>}</section>
    {nameOpen && <ProjectNameDialog busy={working === "fluidlab"} error={modalError} onCancel={() => setNameOpen(false)} onCreate={(name) => void createFluidLab(name)}/>}</main>;
}
